tenant: skierkowski
app: greeter
service: hello
frameworkVersion: ">=1.46.1"
provider:
  name: aws
  runtime: nodejs12.x
  role: arn:aws:iam::192187338582:role/lambda-cloudwatchlogs-lambda-write
functions:
  hello:
    handler: test.hello
    events:
      - http:
          path: hello
          method: post